title: Tractenberg.org
author: Rochelle Tractenberg
email: rochelle.tractenberg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   this is the website of dr. tractenberg
Pronouns: she/her/hers



# social links
twitter_username: rtractenberg # DO NOT include the @ character, or else the build will fail!
github_username:  tractenberg # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
